export const GET_CITY_START = 'GET_CITY_START';
export const GET_CITY_SUCCESS = 'GET_CITY_SUCCESS';
export const GET_CITY_FAILED = 'GET_CITY_FAILED';
export const GET_CITY_WEATHER_DAYS_START = 'GET_CITY_WEATHER_DAYS_START';
export const GET_CITY_WEATHER_DAYS_SUCCESS = 'GET_CITY_WEATHER_DAYS_SUCCESS';
export const GET_CITY_WEATHER_DAYS_FAILED = 'GET_CITY_WEATHER_DAYS_FAILED';
